name: Build Emby Plugin

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: List files in source directory
      run: find src -type f | sort

    - name: Restore dependencies
      run: dotnet restore src/FlagMyCountry.sln
      continue-on-error: false

    - name: Build
      run: dotnet build src/FlagMyCountry.sln -c Release --no-restore
      continue-on-error: false

    - name: List build output
      run: find src -name "*.dll" -type f

    - name: Get artifact path
      id: get_path
      run: |
        PLUGIN_PATH=$(find src -name "FlagMyCountry.dll" -type f | grep -v "obj/" | head -n 1)
        if [ -z "$PLUGIN_PATH" ]; then
          echo "ERROR: Could not find FlagMyCountry.dll"
          exit 1
        fi
        echo "PLUGIN_PATH=$PLUGIN_PATH" >> $GITHUB_ENV
        echo "Found plugin at: $PLUGIN_PATH"

    - name: Create artifact directory
      run: mkdir -p ./artifacts

    - name: Copy artifact
      run: |
        cp "${{ env.PLUGIN_PATH }}" ./artifacts/FlagMyCountry.dll
        ls -la ./artifacts/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: FlagMyCountry-plugin
        path: ./artifacts/FlagMyCountry.dll

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ./artifacts/FlagMyCountry.dll
        token: ${{ secrets.GITHUB_TOKEN }}
