name: Build Emby Plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    
    - name: Restore dependencies
      run: dotnet restore src/FlagMyCountry.sln
    
    - name: Build
      run: dotnet build src/FlagMyCountry.sln -c Release --no-restore
    
    - name: Upload plugin artifact
      uses: actions/upload-artifact@v2  # Changed from v3 to v2
      with:
        name: FlagMyCountry-plugin
        path: src/FlagMyCountry/bin/Release/netstandard2.0/FlagMyCountry.dll
        
    - name: Create Release
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
        
    - name: Upload Release Asset
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: src/FlagMyCountry/bin/Release/netstandard2.0/FlagMyCountry.dll
        asset_name: FlagMyCountry.dll
        asset_content_type: application/octet-stream
